server:
  port: 8087

spring:
  application:
    name: opcua-operation-service

logging:
  level:
    root: INFO
    com.openindustryproject: DEBUG

simulation:
  mqtt:
    enabled: true
    broker-url: tcp://mosquitto:1883
    client-id: simulation-operation-service
    qos: 1
    topic-template: simulation/{stationId}/operations/{operation}
    conveyor:
      running-topic: simulation/Station_01/operations/conveyorRunning
      speed-topic: simulation/Station_01/operations/conveyorSpeed
