server:
  port: 8087

spring:
  application:
    name: operation-delegation-service

logging:
  level:
    root: INFO
    com.openindustryproject: DEBUG

simulation:
  mqtt:
    enabled: true
    broker-url: tcp://mosquitto:1883
    client-id: operation-delegation-service
    qos: 1
    station-topic-template: simulation/{stationId}/operations/{operation}
    robot-topic-template: simulation/robots/{robotId}/operations/{operation}
